# Generated by Django 5.2.7 on 2025-10-20 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id_webtoon', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('id_creador', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('genero', models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('FANTASIA', 'Fantasía'), ('ROMANCE', 'Romance'), ('TERROR', 'Terror'), ('MISTERIO', 'Misterio'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('PAUSADO', 'Pausado')], default='EN_CURSO', max_length=20)),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now)),
                ('portada_url', models.URLField(max_length=255)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
