# Generated by Django 5.2.7 on 2025-10-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='id_creador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
